spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  data:
    redis:
      host: ${SPRING_REDIS_HOST}
      port: ${SPRING_REDIS_PORT}

equibalance:
  jwt:
    secret: ${JWT_SECRET}
  price:
    alphavantage:
      api-key: ${ALPHAVANTAGE_API_KEY:demo}
